//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EclipseLibrary.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EclipseLibrary.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Called when something is clicked in a grid containing a SelectCheckBoxField
        ///function SelectCheckBoxField_GridClick(e) {
        ///    var checked = $(e.target).is(&apos;:checked&apos;);
        ///    var $grid = $(this);
        ///    if ($(e.target).is(&apos;.gvex-header-checkbox&apos;)) {
        ///        var $container = $(e.target).closest(&apos;tbody&apos;);
        ///        if ($container.length == 0) {
        ///            // This is the real header check box. Use all tbodies within the grid
        ///            $container = $(&apos;&gt; tbody&apos;, this);
        ///        }
        ///        // Check/uncheck al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectCheckBoxFieldScripts {
            get {
                return ResourceManager.GetString("SelectCheckBoxFieldScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function($) {
        ///    // Private functions
        ///    // Toggle the direction of the icon
        ///    // event.target is the icon which was clicked
        ///    function OnIconClick(event) {
        ///        if (!$(event.target).is(&apos;span.ui-icon&apos;)) {
        ///            // Ignore the click
        ///            return;
        ///        }
        ///        if ($(event.target).hasClass(&apos;ui-icon-triangle-1-n&apos;)) {
        ///            $(event.target).removeClass(&apos;ui-icon-triangle-1-n&apos;).addClass(&apos;ui-icon-triangle-1-s&apos;).attr(&apos;title&apos;, &apos;Descending&apos;);
        ///        } else {
        ///            $(ev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SortColumnsChooserScript {
            get {
                return ResourceManager.GetString("SortColumnsChooserScript", resourceCulture);
            }
        }
    }
}
